sudo: false
language: elixir

matrix:
  include:
    - elixir: 1.3
      otp_release: 18.3
    - elixir: 1.4
      otp_release: 19.3
    - elixir: 1.5
      otp_release: 20.3
    - elixir: 1.6
      otp_release: 20.3

script: 
  - mix do deps.get, compile, test